trigger:
- main

pool:
  name: 'Default'

variables:
  imageRepository: 'edwardpinzon651/hello-world'
  containerRegistry: 'miregistro1996.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'
  azureSubscription: 'AzureServiceConnection'
  resourceGroup: 'miNuevoGrupoDeRecursos'
  aksCluster: 'miClusterAKS'

stages:
- stage: Checkout
  jobs:
  - job: Checkout
    steps:
    - checkout: self
      displayName: 'Clonar repositorio'

- stage: SetupNode
  dependsOn: Checkout
  jobs:
  - job: SetupNode
    steps:
    - task: UseNode@1
      inputs:
        versionSpec: '14.x'
        checkLatest: true
      displayName: 'Configurar Node.js'

- stage: InstallDependencies
  dependsOn: SetupNode
  jobs:
  - job: InstallDependencies
    steps:
    - script: |
        npm install
      displayName: 'Instalar dependencias'

- stage: LintCode
  dependsOn: InstallDependencies
  jobs:
  - job: LintCode
    steps:
    - script: |
        npm run lint
      displayName: 'Ejecutar an치lisis de c칩digo est치tico'

- stage: BuildDockerImage
  dependsOn: LintCode
  jobs:
  - job: BuildDockerImage
    steps:
    - script: |
        docker build -t $(imageRepository):$(tag) -f $(dockerfilePath) .
        docker tag $(imageRepository):$(tag) $(containerRegistry)/$(imageRepository):$(tag)
      displayName: 'Construir imagen Docker'

- stage: PushDockerImage
  dependsOn: BuildDockerImage
  jobs:
  - job: PushDockerImage
    steps:
    - task: Docker@2
      inputs:
        command: 'login'
        containerRegistry: 'dockerRegistryConnection'
      displayName: 'Iniciar sesi칩n en el registro de Docker'

    - script: |
        docker push $(containerRegistry)/$(imageRepository):$(tag)
      displayName: 'Enviar imagen Docker al registro'

- stage: Deploy
  dependsOn: PushDockerImage
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(resourceGroup) --name $(aksCluster)
          kubectl apply -f deployment.yaml
      displayName: 'Desplegar en AKS'
