trigger:
- main

pool:
  name: 'Default'

variables:
  imageRepository: 'edwardpinzon651/hello-world'
  containerRegistry: 'miregistro1996.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'
  azureSubscription: 'AzureServiceConnection'
  resourceGroup: 'miNuevoGrupoDeRecursos'
  aksCluster: 'miClusterAKS'
  sonarQubeEndpoint: 'Sonarqube'  # Nombre de tu conexión de servicio a SonarQube
  sonarQubeProjectKey: 'pruebaultima-key'  # Clave del proyecto en SonarQube
  sonarQubeProjectName: 'pruebaultima'  # Nombre del proyecto en SonarQube

stages:
- stage: Checkout
  jobs:
  - job: Checkout
    steps:
    - checkout: self
      displayName: 'Clonar repositorio'

- stage: Install
  dependsOn: Checkout
  jobs:
  - job: Install
    steps:
    - task: UseNode@1
      inputs:
        versionSpec: '14.x'
        checkLatest: true

    - script: |
        npm install
      displayName: 'Instalar dependencias'

- stage: LintCode
  dependsOn: Install
  jobs:
  - job: LintCode
    steps:
    - script: |
        npm run lint
      displayName: 'Ejecutar análisis de código estático'

- stage: TestCode
  dependsOn: LintCode
  jobs:
  - job: TestCode
    steps:
    - script: |
        npm test
      displayName: 'Ejecutar pruebas unitarias'

- stage: SonarQubeAnalysis
  dependsOn: TestCode
  jobs:
  - job: SonarQubeAnalysis
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: '$(sonarQubeEndpoint)'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(sonarQubeProjectKey)'
        cliProjectName: '$(sonarQubeProjectName)'
        cliSources: '.'
      displayName: 'Preparar análisis de SonarQube'

    - task: SonarQubeAnalyze@5
      displayName: 'Ejecutar análisis de SonarQube'

    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'
      displayName: 'Publicar resultados de SonarQube'

- stage: BuildDocker
  dependsOn: SonarQubeAnalysis
  jobs:
  - job: BuildDocker
    steps:
    - script: |
        docker build -t $(imageRepository):$(tag) -f $(dockerfilePath) .
        docker tag $(imageRepository):$(tag) $(containerRegistry)/$(imageRepository):$(tag)
      displayName: 'Construir imagen Docker'

    - task: Docker@2
      inputs:
        command: 'login'
        containerRegistry: 'dockerRegistryConnection'

    - script: |
        docker push $(containerRegistry)/$(imageRepository):$(tag)
      displayName: 'Enviar imagen Docker al registro'

- stage: Deploy
  dependsOn: BuildDocker
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(resourceGroup) --name $(aksCluster)
          kubectl apply -f deployment.yaml
      displayName: 'Desplegar en AKS'
